var mongoose = require('mongoose')
mongoose.connect('mongodb://localhost/nodechat')
exports.Message = mongoose.model('Message', require('./message'))
exports.Room = mongoose.model('Room', require('./room'))
exports.User = mongoose.model('User', require('./user'))